//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chernovik
{
    using System;
    using System.Collections.Generic;
    
    public partial class IDMaterials
    {
        public int Id_Material { get; set; }
        public string Materials { get; set; }
    }
}
