//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chernovik
{
    using System;
    using System.Collections.Generic;
    
    public partial class Production
    {
        public int idProduction { get; set; }
        public Nullable<int> СostPrice { get; set; }
        public Nullable<int> idWorkshop { get; set; }
        public Nullable<int> CountPeople { get; set; }
        public string Materials { get; set; }
        public Nullable<int> idProduct { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Workshop Workshop { get; set; }
    }
}
