//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chernovik
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int id { get; set; }
        public string Firstname { get; set; }
        public string LastName { get; set; }
        public string Middlename { get; set; }
        public Nullable<System.DateTime> DataOfBirth { get; set; }
        public Nullable<int> NumberPasport { get; set; }
        public Nullable<int> SeriaPasport { get; set; }
        public string ScoreBank { get; set; }
        public string NameBank { get; set; }
        public string Family { get; set; }
        public string LevelHealth { get; set; }
    
        public virtual Analyticks Analyticks { get; set; }
        public virtual StaffSpec StaffSpec { get; set; }
    }
}
