//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chernovik
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffSpec
    {
        public int idStaff { get; set; }
        public string PresenceOfSpecialty { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
